### ISSUE TITLE
[FEATURE] Change to a standard licence

### ISSUE THREAD

**Issue by bruce34** [saltstack-formulas/firewalld-formula#35]
I'd like to be able to use this formula as part of DevOps within a company, hosting it on our own git servers (for reasons of no external dependencies), possibly having the ability to change the files as well without having to post them externally (although I'd obviously be happy to provide PR for genuinely usefull additions). IANAL means that I cannot be sure whether the extra clause in the licence file conflicts with our use case.

Even a reply here placating these concerns, again because IANAL, means I still don't know whether we can use it.

The simplest for us would be a change of the LICENSE to be a standard Apache Licence as most other saltstack formulas are. 

Section I'd like removed:
   EXCEPTIONS:
   You MAY NOT upload parts or the whole work of this product on Github or
   any other platform again UNLESS you are in possession of an agreement
   by the author OR use the function called "FORK" provided on Github itself.
   Other parts of the specified license above are not affected.

**Comment by aboe76** [comment]
@bruce34 you should ask @tinuva about this.

**Comment by javierbertoli** [comment]
IANAL either, but I think @tinuva meant to prevent people from copying the formula and uploading it to any PUBLIC platform loosing the history and attributions to the original author/s. I'm deducing that from the UNLESS clause (ask for permission to do it or use FORK, which ensures him the history is preserved).

I don't think @tinuva has any issue with private forking/using/modifying but, in the end, I agree with @aboe76 that @tinuva is the one to answer this in the end.

And I agree with you that changing to a license and permissions similar to those used in the other formulas would be a "Good Thing (TM)".

**Comment by tinuva** [comment]
I think this is a fair request and am happy to remove the 'EXCEPTIONS' section. 

This formula has gone much further than I ever anticipated and since I no longer work as much with Saltstack as I have in the past, I believe its in the best interest of everyone to sync the license to the same default license used in other formulas.

I have already synced up this repository to my own. Give me a day or so and I will update the license and create a pullrequest here.

**Comment by myii** [comment]
@bruce34 Thanks to @tinuva in #37, this formula is now using a standardised license without any exceptions.

**Comment by bruce34** [comment]
Perfect - thanks!
